DB_URL: jdbc:postgresql://localhost:5434/postgres-booking-service
DB_USERNAME: admin
DB_PASSWORD: admin


KEYCLOAK_ISSUER_URI: http://localhost:8081/realms/demo
USER_SERVICE_URL: http://localhost:8080
PROPERTY_SERVICE_URL: http://localhost:8082

SERVER_PORT: 8083