spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-user-service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

KEYCLOAK_ISSUER_URI: http://localhost:8081/realms/demo

server:
  port: 8080